version: "3"

services:
  shop:
    container_name: tablouri_negre_shop
    image: dockware/dev:6.4.5.1
    ports:
      - "80:80" # apache2
      - "443:443" # apache2
      - "22:22" # ssh
      - "8888:8888" # watch admin
      - "9999:9999" # watch storefront
      - "9998:9998" # watch storefront proxy
    volumes:
      - "nfsmount:/var/www/html"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=0

  redis:
    image: redis:6.2.4-alpine
    container_name: redis
    networks:
      - web

  elasticsearch:
    image: elasticsearch:7.5.2
    container_name: tablouri_negre_elasticsearch
    networks:
      - web
    environment:
      - "EA_JAVA_OPTS=-Xms512m -Xms512m"
      - discovery.type=single-node

  mariadb:
    image: mariadb:10.5.12-focal
    container_name: tablouri_negre_mariadb
    networks:
      - web
    ports:
      - "3306:3306"
    volumes:
      - "mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: shopware

  adminer:
    container_name: tablouri_negre_adminer
    image: adminer:latest
    ports:
      - "8181:8080"


## ***********************************************************************
##  PERSISTENT DOCKER VOLUMES
## ***********************************************************************
volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":$PWD/."
  mariadb:
    driver: local

networks:
  web:
    external: false
